"""
Mapeo de calles reales por barrio para cada ciudad.
Garantiza coherencia geográfica entre el barrio y la dirección mostrada.
"""

NEIGHBORHOOD_STREETS = {
    "Madrid": {
        # ── Centro ──
        "Sol": ["Calle del Carmen", "Calle de Preciados", "Calle del Arenal"],
        "Palacio": ["Calle Mayor", "Plaza de Oriente", "Calle de Bailén"],
        "Huertas": ["Calle de las Huertas", "Calle del Príncipe", "Carrera de San Jerónimo"],
        "Barrio de las Letras": ["Calle de Lope de Vega", "Calle de Cervantes", "Calle de Quevedo"],
        "Chueca": ["Calle de Hortaleza", "Calle de Augusto Figueroa", "Calle de Pelayo"],
        "Malasaña": ["Calle del Pez", "Calle de Fuencarral", "Calle de San Andrés"],
        "Embajadores": ["Calle de Embajadores", "Ronda de Toledo", "Glorieta de Embajadores"],
        "Lavapiés": ["Calle de Lavapiés", "Calle del Ave María", "Calle de Argumosa"],
        "La Latina": ["Calle de la Cava Baja", "Calle de Toledo", "Plaza de la Cebada"],
        "El Rastro": ["Calle de la Ribera de Curtidores", "Ronda de Toledo", "Calle del Carnero"],
        "Atocha": ["Calle de Atocha", "Ronda de Atocha", "Glorieta del Emperador Carlos V"],
        # ── Chamberí / Norte centro ──
        "Chamberí": ["Calle de Santa Engracia", "Calle de Eloy Gonzalo", "Calle de Trafalgar"],
        "Trafalgar": ["Calle de Trafalgar", "Calle de Luchana", "Calle de Hartzenbusch"],
        "Alonso Cano": ["Calle de Alonso Cano", "Calle de Ríos Rosas", "Calle de José Abascal"],
        "Arapiles": ["Calle de Arapiles", "Calle de Magallanes", "Calle de Donoso Cortés"],
        "Gaztambide": ["Calle de Gaztambide", "Calle de Meléndez Valdés", "Calle de Hilarión Eslava"],
        "Vallehermoso": ["Calle de Vallehermoso", "Calle de Fernández de los Ríos", "Calle de Blasco de Garay"],
        "Almagro": ["Calle de Almagro", "Calle de Zurbano", "Calle de Génova"],
        "Ríos Rosas": ["Calle de Ríos Rosas", "Calle de Ponzano", "Calle de Joaquín María López"],
        "Cuatro Caminos": ["Glorieta de Cuatro Caminos", "Calle de Bravo Murillo", "Avenida de Reina Victoria"],
        # ── Salamanca / Retiro ──
        "Salamanca": ["Calle de Serrano", "Calle de Velázquez", "Calle de Jorge Juan"],
        "Retiro": ["Calle de Ibiza", "Calle de Narváez", "Calle del Doctor Esquerdo"],
        "Goya": ["Calle de Goya", "Calle de Jorge Juan", "Calle del Conde de Peñalver"],
        "Lista": ["Calle de José Ortega y Gasset", "Calle de Castelló", "Calle de Ayala"],
        "Fuente del Berro": ["Calle de O'Donnell", "Calle de Bocángel", "Calle del Doctor Esquerdo"],
        "La Guindalera": ["Calle de Francisco Silvela", "Calle de Francisco Navacerrada", "Calle de Cartagena"],
        # ── Castellana / Chamartín ──
        "Castellana": ["Paseo de la Castellana", "Calle de Serrano", "Calle de Génova"],
        "Chamartín": ["Paseo de la Castellana", "Calle del Doctor Fleming", "Calle de Mateo Inurria"],
        "Hispanoamérica": ["Avenida de América", "Calle del Príncipe de Vergara", "Calle de Costa Rica"],
        "Nueva España": ["Calle del Doctor Federico Rubio y Galí", "Calle de la Basílica"],
        "Bernabéu": ["Paseo de la Castellana", "Avenida del Condesable de Castilla", "Calle del Padre Damián"],
        "Prosperidad": ["Calle de López de Hoyos", "Calle de Cartagena", "Calle del Doctor Castelo"],
        "Ciudad Jardín": ["Calle de Arturo Soria", "Calle de Alfonso XIII", "Calle de Duque de Sevilla"],
        "Concepción": ["Calle de José del Hierro", "Calle de Alcalde Sáinz de Baranda"],
        "San Juan Bautista": ["Calle de Ulises", "Calle de Tánger", "Calle de Nepal"],
        # ── Moncloa / Argüelles ──
        "Moncloa-Aravaca": ["Calle de la Princesa", "Calle de Alberto Aguilera", "Calle de Isaac Peral"],
        "Argüelles": ["Calle de la Princesa", "Calle del Marqués de Urquijo", "Calle de Alberto Aguilera"],
        "Ciudad Universitaria": ["Avenida Complutense", "Avenida de Séneca", "Calle del Profesor Aranguren"],
        # ── Tetuán ──
        "Tetuán": ["Calle de Bravo Murillo", "Calle del Marqués de Viana", "Calle del Topete"],
        "Almenara": ["Calle de Francos Rodríguez", "Calle de la Virgen del Puig"],
        "Berruguete": ["Calle de Berruguete", "Calle de Palencia", "Calle del Aviador Zorita"],
        "Valdeacederas": ["Calle de Lérida", "Calle de Castilla", "Calle de Marqués de Viana"],
        "Ventilla": ["Calle de Matías Turrión", "Calle de San Germán"],
        # ── Fuencarral / Norte periférico ──
        "El Pilar": ["Avenida de Betanzos", "Calle del Cardenal Herrera Oria"],
        "Peñagrande": ["Calle de Monforte de Lemos", "Avenida de la Vaguada"],
        "Barrio del Pilar": ["Avenida de Betanzos", "Calle del Doctor Federico Rubio y Galí"],
        "Valverde": ["Calle de Navalcarnero", "Calle de Valverde"],
        "Fuentelareina": ["Calle de Fuentelareina", "Calle de las Suertes"],
        "Mirasierra": ["Calle del Puerto de Somport", "Calle de Hoyos del Espino"],
        "Las Tablas": ["Avenida del Camino de Santiago", "Calle de la Caléndula"],
        "Sanchinarro": ["Avenida de Francisco Pi y Margall", "Calle de la Princesa de Éboli"],
        "Virgen del Cortijo": ["Calle del Virgen del Cortijo", "Calle de Saconia"],
        "Virgen de Begoña": ["Calle de Ginzo de Limia", "Calle de Sinesio Delgado"],
        "Piovera": ["Avenida de los Madroños", "Calle del Monasterio de El Paular"],
        "Palomas": ["Calle de las Palomas", "Calle de María Tudor"],
        # ── Hortaleza / Ciudad Lineal ──
        "Hortaleza": ["Calle de López de Hoyos", "Calle de Arturo Soria", "Calle de Mar de Aral"],
        "Canillejas": ["Calle de Alcalá", "Avenida de Canillejas a Vicálvaro"],
        "Pueblo Nuevo": ["Calle de Alcalá", "Calle de Ascao", "Calle de Suecia"],
        "Las Rosas": ["Calle de los Hermanos García Noblejas", "Calle de Suecia"],
        "Quintana": ["Calle de Alcalá", "Calle de Quintana"],
        "Simancas": ["Calle de Simancas", "Calle de los Hermanos García Noblejas"],
        "La Elipa": ["Calle de la Elipa", "Calle del General Maroto"],
        # ── Arganzuela / Sur centro ──
        "Arganzuela": ["Paseo de las Delicias", "Ronda de Valencia", "Calle de Embajadores"],
        "Delicias": ["Paseo de las Delicias", "Calle del Ferrocarril", "Calle de Méndez Álvaro"],
        "Chopera": ["Paseo de la Chopera", "Calle de Áncora", "Calle del Ferrocarril"],
        "Legazpi": ["Calle de Antonio López", "Avenida del Manzanares", "Paseo de la Chopera"],
        # ── Carabanchel / Latina ──
        "Carabanchel": ["Calle del General Ricardos", "Calle de Eugenia de Montijo", "Avenida de los Poblados"],
        "Comillas": ["Calle de Comillas", "Calle del General Ricardos"],
        "Oporto": ["Calle de Antonio Leyva", "Avenida de Oporto", "Calle de Batalla del Salado"],
        # ── Usera ──
        "Usera": ["Calle de Marcelo Usera", "Calle de Dolores Barranco", "Avenida de Rafaela Ybarra"],
        "Pradolongo": ["Calle de Pradolongo", "Avenida de Rafaela Ybarra"],
        # ── Vallecas / Sureste ──
        "Vallecas": ["Avenida de la Albufera", "Calle de Sierra Gorda", "Calle del Monte Igueldo"],
        "Palomeras": ["Calle de Sierra de Guadalupe", "Calle de Peña Prieta"],
        "Portazgo": ["Calle de Sierra de Albarracín", "Calle de Sierra de Gata"],
        "Numancia": ["Avenida de la Albufera", "Calle de Numancia"],
        "San Diego": ["Calle de Peironcely", "Calle del Doctor Martín Arévalo"],
        "Entrevías": ["Calle de Payaso Fofó", "Calle de Pierrot"],
        "San Cristóbal": ["Calle de San Zacarías", "Calle de la Virgen de la Alegría"],
        # ── Este ──
        "Moratalaz": ["Avenida de Moratalaz", "Calle del Arroyo de la Media Legua"],
        "Vicálvaro": ["Avenida de Canillejas a Vicálvaro", "Calle del Real de Arganda"],
    },
    "Barcelona": {
        # ── Ciutat Vella ──
        "Ciutat Vella": ["La Rambla", "Via Laietana", "Carrer de Ferran"],
        "El Born": ["Passeig del Born", "Carrer de la Princesa", "Carrer de Montcada"],
        "El Raval": ["Carrer de l'Hospital", "Carrer de Joaquín Costa", "Rambla del Raval"],
        "La Barceloneta": ["Passeig Marítim", "Carrer de l'Almirall Cervera", "Carrer de Balboa"],
        # ── Eixample ──
        "Eixample": ["Carrer de Mallorca", "Carrer de València", "Carrer d'Aragó"],
        "Sagrada Família": ["Carrer de Provença", "Carrer de Sardenya", "Carrer de la Marina"],
        "La Sagrada Família": ["Carrer de Provença", "Carrer de Sardenya", "Carrer de la Marina"],
        "La Dreta de l'Eixample": ["Passeig de Gràcia", "Carrer de Pau Claris", "Carrer de Roger de Llúria"],
        "L'Antiga Esquerra de l'Eixample": ["Carrer d'Enric Granados", "Carrer del Consell de Cent"],
        "La Nova Esquerra de l'Eixample": ["Carrer del Comte d'Urgell", "Carrer de Villarroel"],
        "Sant Antoni": ["Ronda de Sant Antoni", "Carrer del Comte d'Urgell", "Carrer del Parlament"],
        "El Fort Pienc": ["Carrer d'Alí Bei", "Carrer de Nàpols", "Carrer de Ribes"],
        "Camp d'en Grassot": ["Carrer de Camp d'en Grassot", "Carrer de Bruniquer"],
        # ── Gràcia ──
        "Gràcia": ["Gran de Gràcia", "Carrer de Verdi", "Travessera de Gràcia"],
        "Vila de Gràcia": ["Carrer de Verdi", "Plaça del Sol", "Carrer de Torrent de l'Olla"],
        "La Salut": ["Carrer de la Salut", "Carrer de Torrent de les Flors"],
        "El Coll": ["Carrer de l'Aldea", "Carrer del Santuari"],
        "Vallcarca": ["Avinguda de Vallcarca", "Carrer de Bolívar"],
        "El Putget": ["Carrer del Putget", "Carrer de Manacor"],
        # ── Sarrià–Sant Gervasi ──
        "Sarrià-Sant Gervasi": ["Via Augusta", "Carrer de Muntaner", "Carrer de Balmes"],
        "Sant Gervasi": ["Via Augusta", "Carrer de Santaló", "Carrer de Muntaner"],
        "Sarrià": ["Carrer Major de Sarrià", "Passeig de la Bonanova"],
        "Les Tres Torres": ["Carrer del Doctor Roux", "Carrer de Calatrava"],
        "La Bonanova": ["Passeig de la Bonanova", "Carrer de Ganduxer"],
        "Pedralbes": ["Avinguda de Pedralbes", "Avinguda de Pearson"],
        # ── Les Corts ──
        "Les Corts": ["Travessera de Les Corts", "Carrer de Numància", "Avinguda de Sarrià"],
        "Camp Nou": ["Avinguda d'Arístides Maillol", "Travessera de Les Corts"],
        # ── Sants-Montjuïc ──
        "Sants-Montjuïc": ["Carrer de Sants", "Carrer de la Creu Coberta", "Passeig de l'Exposició"],
        "Sants": ["Carrer de Sants", "Carrer de la Creu Coberta"],
        "Poble Sec": ["Avinguda del Paral·lel", "Carrer de Blai", "Carrer de Tapioles"],
        "Badal": ["Carrer de Badal", "Carrer de Sants"],
        "La Bordeta": ["Carrer de la Bordeta", "Carrer de Constitució"],
        "Hostafrancs": ["Carrer de la Creu Coberta", "Carrer de Moianès"],
        "La Vinya": ["Carrer de la Mare de Déu del Port", "Passeig de la Zona Franca"],
        "Can Clos": ["Passeig de la Zona Franca", "Carrer del Foc"],
        "Font de la Guatlla": ["Carrer de la Font Florida", "Carrer de Magòria"],
        "Zona Franca": ["Passeig de la Zona Franca", "Carrer dels Motores"],
        # ── Sant Martí ──
        "Sant Martí": ["Rambla de Poblenou", "Carrer de Pallars", "Carrer de Llull"],
        "Poblenou": ["Rambla del Poblenou", "Carrer de Marià Aguiló", "Carrer de Pujades"],
        "Clot": ["Carrer del Clot", "Plaça del Clot", "Carrer de Rogent"],
        "El Camp de l'Arpa": ["Carrer del Camp de l'Arpa", "Carrer de Freser"],
        "El Parc i la Llacuna": ["Carrer de Pujades", "Carrer del Doctor Trueta"],
        "La Vila Olímpica": ["Avinguda d'Icària", "Carrer de la Marina"],
        "Diagonal Mar": ["Avinguda Diagonal", "Carrer de Llull"],
        "El Besos": ["Rambla de Prim", "Carrer de Llull"],
        "El Maresme": ["Carrer de Llull", "Carrer de Cristóbal de Moura"],
        "La Verneda i la Pau": ["Carrer de Santander", "Carrer de Binèfar"],
        "Navas": ["Carrer de Navas de Tolosa", "Carrer de Biscaia"],
        # ── Horta-Guinardó ──
        "Horta-Guinardó": ["Carrer de Dante", "Ronda del Guinardó"],
        "El Carmel": ["Carrer del Carmel", "Carrer de Dante"],
        "Horta": ["Carrer d'Horta", "Carrer de Chapí"],
        "El Baix Guinardó": ["Carrer del Guinardó", "Carrer de Lepant"],
        "Can Baró": ["Carrer de Can Baró", "Ronda del Guinardó"],
        "El Guinardó": ["Ronda del Guinardó", "Carrer del Guinardó"],
        "La Font d'en Fargues": ["Carrer de Mühlberg", "Carrer de Pere d'Artés"],
        "La Teixonera": ["Carrer de la Teixonera", "Carrer del Dante"],
        "Sant Genís dels Agudells": ["Passeig de la Vall d'Hebron", "Carrer de Sant Genís"],
        "Montbau": ["Passeig de la Vall d'Hebron", "Carrer de l'Arquitectura"],
        "La Vall d'Hebron": ["Passeig de la Vall d'Hebron", "Carrer de Jorge Manrique"],
        "La Clota": ["Carrer de la Clota", "Carrer d'Horta"],
        # ── Nou Barris ──
        "Nou Barris": ["Via Júlia", "Passeig de Fabra i Puig"],
        "Vilapicina": ["Carrer de Vilapicina", "Passeig de Maragall"],
        "Porta": ["Via Júlia", "Passeig de Fabra i Puig"],
        "El Turó de la Peira": ["Via Júlia", "Carrer de Beret"],
        "Can Peguera": ["Passeig de Fabra i Puig", "Carrer d'Olesa"],
        "La Guineueta": ["Passeig de Valldaura", "Via Júlia"],
        "Canyelles": ["Via Favència", "Carrer d'Antonio Machado"],
        "Les Roquetes": ["Carrer de Mina de la Ciutat", "Via Favència"],
        "Verdun": ["Carrer de Verdun", "Passeig de Verdun"],
        "La Prosperitat": ["Via Júlia", "Carrer de Santa Engràcia"],
        "La Trinitat Nova": ["Via Favència", "Carrer d'Aiguablava"],
        "Torre Baró": ["Carrer del Vesuvi", "Passatge de l'Àngel"],
        "Ciutat Meridiana": ["Avinguda de Rasos de Peguera", "Carrer de Vallcivera"],
        "Vallbona": ["Carrer de Vallbona", "Carrer d'Oristà"],
        # ── Sant Andreu ──
        "Sant Andreu": ["Gran de Sant Andreu", "Carrer de Segre"],
        "Sant Andreu de Palomar": ["Gran de Sant Andreu", "Carrer del Segre"],
        "La Sagrera": ["Carrer de la Sagrera", "Carrer de Berenguer de Palou"],
        "La Trinitat Vella": ["Carrer de Garigliano", "Via de Bàrcino"],
        "Baró de Viver": ["Carrer de Quito", "Passeig de Santa Coloma"],
        "El Bon Pastor": ["Carrer de Llinars del Vallès", "Carrer de Sant Adrià"],
        "El Congrés i els Indians": ["Carrer del Congrés", "Carrer de la Independència"],
    },
    "Valencia": {
        "Ruzafa": ["Carrer de Sueca", "Carrer de Cuba", "Carrer de Cadis"],
        "El Carmen": ["Carrer dels Cavallers", "Plaça del Tossal", "Carrer de les Blanqueries"],
        "L'Eixample": ["Gran Via del Marqués del Túria", "Carrer de Colón", "Carrer de Cirilo Amorós"],
        "Benimaclet": ["Carrer de Barón de San Petrillo", "Carrer del Doctor Vicente Zaragozá"],
        "Ciutat Vella": ["Carrer de la Pau", "Plaça de l'Ajuntament", "Carrer de Sant Vicent Màrtir"],
        "Campanar": ["Avinguda de Campanar", "Carrer del Mestre Rodrigo"],
        "Patraix": ["Carrer de Jaca", "Carrer d'Ángel Villena"],
        "Jesús": ["Carrer de Jesús", "Carrer de Maximiliano Thous"],
        "Poblats Marítims": ["Carrer de la Reina", "Passeig Marítim"],
        "El Cabanyal": ["Carrer de la Reina", "Carrer del Doctor Lluch", "Carrer de Josep Benlliure"],
        "La Saïdia": ["Avinguda de la Constitució", "Carrer de Sagunt"],
        "Extramurs": ["Gran Via de Fernando el Católico", "Carrer de Guillem de Castro"],
        "Quatre Carreres": ["Avinguda de la Plata", "Carrer del Pintor Maella"],
        "Algirós": ["Avinguda de Blasco Ibáñez", "Carrer del Doctor Manuel Candela"],
        "Gran Vía": ["Gran Via de les Germanies", "Carrer de Russafa"],
        "Malvarrosa": ["Passeig Marítim", "Carrer d'Isabel de Villena"],
        "Las Arenas": ["Passeig Marítim", "Carrer d'Eugènia Viñes"],
        "Nazaret": ["Carrer de Nazaret", "Carrer dels Tramviaris"],
        "El Grau": ["Avinguda del Port", "Carrer del Progrés"],
        "Natzaret": ["Carrer de Nazaret", "Carrer dels Tramviaris"],
        "La Malva-rosa": ["Passeig Marítim", "Carrer de Mendizábal"],
        "Cañamelar": ["Carrer del Doctor Lluch", "Carrer de la Reina"],
        "Orriols": ["Carrer de la Safor", "Carrer de l'Enginyer José Sirera"],
        "Torrefiel": ["Carrer de l'Escultor Piquer", "Carrer de Torrefiel"],
        "Marxalenes": ["Carrer de Marxalenes", "Avinguda de Burjassot"],
        "La Zaidía": ["Carrer de Sagunt", "Carrer de la Safor"],
        "Morvedre": ["Carrer de Morvedre", "Carrer de Sagunt"],
        "Trinitat": ["Avinguda de la Constitució", "Carrer de la Trinitat"],
        "Tormos": ["Carrer de Tormos", "Carrer de l'Arquebisbe Company"],
        "Sant Pau": ["Carrer de Sant Pau", "Carrer de Sagunt"],
        "El Calvari": ["Carrer del Calvari", "Carrer de Manuel Candela"],
        "La Creu del Grau": ["Carrer de Burriana", "Carrer de l'Enginyer Fausto Elio"],
        "Camí Fondo": ["Carrer de Camí Fondo", "Avinguda del Port"],
        "Penya-roja": ["Carrer de Penya-roja", "Avinguda de Blasco Ibáñez"],
        "L'Illa Perduda": ["Carrer de Jeroni de Montsoriu", "Carrer d'Eolo"],
        "Ciutat Jardí": ["Avinguda de Blasco Ibáñez", "Carrer de la Ciutat Jardí"],
        "Aiora": ["Carrer d'Aiora", "Carrer d'Eolo"],
        "La Carrasca": ["Carrer de la Carrasca", "Carrer de Juan Ramón Jiménez"],
        "Beniferri": ["Camí de Moncada", "Carrer de Beniferri"],
        "Benimamet": ["Carrer Major de Benimamet", "Avinguda de Burjassot"],
        "Benissepena": ["Camí Vell de Godella", "Carrer de Benissepena"],
        "El Saler": ["Avinguda dels Pinars", "Carrer del Saler"],
        "L'Hort de Senabre": ["Carrer de Josep Maria Haro", "Carrer del Pintor Genaro Lahuerta"],
        "La Creu Coberta": ["Carrer de la Creu Coberta", "Carrer d'Ángel Villena"],
        "Sant Marcel·lí": ["Carrer de Fontanars dels Alforins", "Carrer de Sant Marcel·lí"],
        "Camí Real": ["Carrer del Camí Real", "Camí Reial"],
        "Safranar": ["Carrer del Safranar", "Carrer d'Ángel Villena"],
        "Favara": ["Carrer de Favara", "Carrer dels Horts"],
        "Vara de Quart": ["Carrer de Vara de Quart", "Carrer del Convent de Santa Clara"],
        "Soternes": ["Avinguda del Cid", "Carrer de Soternes"],
        "Arrancapins": ["Gran Via de Fernando el Católico", "Carrer d'Arrancapins"],
        "La Roqueta": ["Carrer de Xàtiva", "Carrer de la Roqueta"],
        "La Petxina": ["Gran Via del Marqués del Túria", "Carrer de la Petxina"],
    },
    "Sevilla": {
        "Triana": ["Calle Betis", "Calle San Jacinto", "Calle Pureza"],
        "Los Remedios": ["Avenida de la República Argentina", "Calle Asunción", "Calle Virgen de Luján"],
        "Nervión": ["Calle Luis Montoto", "Avenida de Kansas City", "Calle Felipe II"],
        "Santa Cruz": ["Calle Mateos Gago", "Calle Ximénez de Enciso", "Plaza de los Venerables"],
        "Macarena": ["Calle Feria", "Calle Resolana", "Calle Don Fadrique"],
        "San Bernardo": ["Avenida de Carlos V", "Calle Demetrio de los Ríos"],
        "Alameda": ["Alameda de Hércules", "Calle Amor de Dios", "Calle Relator"],
        "El Arenal": ["Calle García de Vinuesa", "Calle Adriano", "Paseo de Colón"],
        "San Lorenzo": ["Calle San Lorenzo", "Plaza del Museo"],
        "Bermejales": ["Avenida de la Palmera", "Calle Torcuato Luca de Tena"],
        "Heliópolis": ["Avenida de la Palmera", "Calle de la Pirotecnia"],
        "Tablada": ["Calle Club de Campo", "Avenida de Tablada"],
        "Cerro del Águila": ["Avenida de la Cruz del Campo", "Calle Luis Ortiz Muñoz"],
        "Pino Montano": ["Avenida de Pino Montano", "Calle Doctor Marañón"],
        "El Porvenir": ["Calle Porvenir", "Avenida de la Borbolla"],
        "Felipe II": ["Calle Felipe II", "Calle Marqués de Nervión"],
        "Huerta del Rey": ["Avenida de la Buhaira", "Calle San Francisco Javier"],
        "Bami": ["Calle Bami", "Avenida de la Palmera"],
        "Palmas Altas": ["Calle Palmas Altas", "Avenida de Palmas Altas"],
        "Palmete": ["Calle Palmete", "Calle Ifni"],
        "Juan XXIII": ["Avenida de Juan XXIII", "Calle Cardenal Ilundáin"],
        "La Paz": ["Calle Federico Mayo Gayarre", "Avenida de la Paz"],
        "Los Carteros": ["Calle Carteros", "Calle Virgen de las Montañas"],
        "Amate": ["Calle Amate", "Avenida de Andalucía"],
        "El Juncal": ["Calle Juncal", "Calle del Torneo"],
        "La Plata": ["Calle La Plata", "Calle Cefiro"],
        "Rochelambert": ["Calle Rochelambert", "Avenida de Hytasa"],
        "Torreblanca": ["Avenida de Torreblanca", "Calle Guadalbullón"],
        "Polígono Norte": ["Avenida de San Lázaro", "Calle Tesalónica"],
        "Valdezorras": ["Calle Valdezorras", "Avenida de las Ciencias"],
        "Sevilla Este": ["Avenida de las Ciencias", "Calle Copérnico"],
        "El Cano": ["Calle del Cano", "Avenida de Miraflores"],
        "Prados de San Sebastián": ["Avenida del Cid", "Paseo de las Delicias"],
        "El Tardón": ["Calle Tardón", "Calle Pagés del Corro"],
        "Los Pajaritos": ["Calle Pajaritos", "Avenida de la Paz"],
        "Bellavista": ["Avenida de Bellavista", "Calle Marruecos"],
        "La Oliva": ["Calle Oliva", "Calle Miraflores"],
    },
    "Málaga": {
        "Centro Histórico": ["Calle Larios", "Calle Granada", "Calle Nueva"],
        "La Malagueta": ["Paseo de Reding", "Calle Maestranza"],
        "El Palo": ["Calle El Palo", "Paseo Marítimo de El Palo"],
        "Pedregalejo": ["Calle Pintor Sorolla", "Paseo Marítimo de Pedregalejo"],
        "Teatinos": ["Avenida de Jorge Luis Borges", "Calle Compositor Lehmberg Ruiz"],
        "Huelin": ["Paseo Marítimo Antonio Machado", "Calle Héroe de Sostoa"],
        "Ciudad Jardín": ["Paseo de Martiricos", "Calle Jacinto Verdaguer"],
        "Carranque": ["Calle Carranque", "Avenida de Fátima"],
        "El Candado": ["Calle El Candado", "Camino de El Palo"],
        "Puerto de la Torre": ["Calle Camino Viejo de Churriana", "Avenida Juan XXIII"],
        "Campanillas": ["Calle de Campanillas", "Avenida de José Ortega y Gasset"],
        "La Rosaleda": ["Avenida de Martiricos", "Calle Donoso Cortés"],
        "Cruz de Humilladero": ["Calle Mármoles", "Avenida de la Aurora"],
        "Babel": ["Calle Babel", "Calle Cuarteles"],
        "La Luz": ["Calle La Luz", "Calle Cruz Verde"],
        "El Molinillo": ["Calle Ollerías", "Calle Refino"],
        "La Victoria": ["Paseo de Reding", "Calle Victoria"],
        "El Ejido": ["Calle El Ejido", "Paseo del Parque"],
        "Capuchinos": ["Calle Capuchinos", "Calle Cister"],
        "La Merced": ["Plaza de la Merced", "Calle Álamos"],
        "San Felipe Neri": ["Calle San Felipe Neri", "Calle Beatas"],
        "La Trinidad": ["Calle Trinidad", "Calle Mármoles"],
        "Perchel Norte": ["Alameda Principal", "Calle Cuarteles"],
        "Perchel Sur": ["Calle Héroe de Sostoa", "Alameda de Colón"],
        "La Goleta": ["Calle La Goleta", "Calle Compañía"],
        "El Bulto": ["Calle Del Bulto", "Paseo Marítimo Antonio Machado"],
        "Churriana": ["Avenida del Comandante García Morato", "Calle de Churriana"],
        "Olías": ["Calle de Olías", "Camino de Olías"],
        "Los Alamos": ["Calle Los Álamos", "Calle Pizarro"],
        "Los Ramos": ["Calle Los Ramos", "Avenida Juan XXIII"],
        "Nuevo San Andrés": ["Calle Pacífico", "Avenida de Fátima"],
        "San Andrés": ["Calle San Andrés", "Avenida de la Aurora"],
        "Miraflores de los Ángeles": ["Calle Miraflores de los Ángeles", "Calle Periodista García Aguilar"],
        "Cerrado de Calderón": ["Calle Cerrado de Calderón", "Calle Salvador Allende"],
        "El Cónsul": ["Calle del Cónsul", "Calle Héroe de Sostoa"],
        "El Limonar": ["Paseo del Limonar", "Calle Pintor Nogales"],
        "La Caleta": ["Calle La Caleta", "Paseo de Sancha"],
        "Sacaba": ["Paseo Marítimo Antonio Machado", "Calle Pacífico"],
    },
    "Bilbao": {
        "Casco Viejo": ["Calle de la Tendería", "Calle Somera", "Plaza Nueva"],
        "Abando": ["Gran Vía de Don Diego López de Haro", "Calle de Ercilla"],
        "Indautxu": ["Alameda de Urquijo", "Calle de Licenciado Poza"],
        "Deusto": ["Avenida de las Universidades", "Calle Ramón y Cajal"],
        "San Ignacio": ["Calle San Ignacio de Loyola", "Avenida del Ejército"],
        "Rekalde": ["Calle de Gordoniz", "Avenida de Rekalde"],
        "Zazpikaleak": ["Calle de Iparraguirre", "Calle de Diputación"],
        "Begoña": ["Calle de la Virgen de Begoña", "Calle Zabalbide"],
        "Santutxu": ["Calle de Santutxu", "Calle Zabalburu"],
        "Basurto": ["Avenida de Montevideo", "Calle de la Autonomía"],
    },
    "Alicante": {
        "Centro": ["Rambla de Méndez Núñez", "Avenida de Maisonnave", "Calle San Fernando"],
        "Playa de San Juan": ["Avenida de Niza", "Calle San Juan de Ávila"],
        "El Campello": ["Avenida Jaime I", "Calle San Bartolomé"],
        "Cabo de las Huertas": ["Calle Cabo de las Huertas", "Avenida de la Costa Blanca"],
        "Carolinas": ["Calle de Foglietti", "Calle de Reyes Católicos"],
        "Benalúa": ["Avenida de la Estación", "Calle de Benalúa"],
        "Florida": ["Calle de Babel", "Calle de San Mateo"],
        "San Blas": ["Calle de San Blas", "Calle de Canalejas"],
        "Altozano": ["Calle del Profesor Loustau", "Avenida de Altozano"],
        "Villafranqueza": ["Calle Mayor de Villafranqueza", "Calle de Elche"],
    },
    "Zaragoza": {
        "Centro": ["Paseo de la Independencia", "Calle Alfonso I", "Calle Don Jaime I"],
        "Delicias": ["Avenida de Madrid", "Calle de Duquesa Villahermosa"],
        "San José": ["Avenida de San José", "Calle de Tomás Bretón"],
        "Las Fuentes": ["Avenida de las Fuentes", "Calle de Salvador Minguijón"],
        "El Rabal": ["Calle de Miguel Servet", "Calle de San Juan de la Peña"],
        "Universidad": ["Paseo de Fernando el Católico", "Calle del Doctor Cerrada"],
        "Actur-Rey Fernando": ["Calle de María Zambrano", "Avenida de Alcalde Caballero"],
        "La Almozara": ["Avenida de la Almozara", "Calle de Pablo Gargallo"],
        "Oliver-Valdefierro": ["Calle de Oliver", "Avenida de Navarra"],
        "Torrero-La Paz": ["Avenida de América", "Calle de Fray Julián Garcés"],
    },
    "Granada": {
        "Albaicín": ["Carrera del Darro", "Cuesta del Chapiz", "Calle Calderería Nueva"],
        "Centro": ["Gran Vía de Colón", "Calle Recogidas", "Calle Reyes Católicos"],
        "Realejo": ["Calle Pavaneras", "Campo del Príncipe"],
        "Ronda": ["Camino de Ronda", "Calle Pedro Antonio de Alarcón"],
        "Beiro": ["Calle Beiro", "Avenida de Dílar"],
        "Zaidín": ["Calle Palencia", "Calle Recogidas"],
        "Chana": ["Calle Chana", "Avenida de Andalucía"],
        "Genil": ["Paseo del Violón", "Calle Emperador Carlos V"],
        "Figares": ["Calle Figares", "Calle San Antón"],
        "Camino de Ronda": ["Camino de Ronda", "Calle Cruz de Lagos"],
    },
    "Murcia": {
        "Centro": ["Gran Vía del Escultor Salzillo", "Calle Trapería", "Calle Platería"],
        "El Carmen": ["Calle del Carmen", "Avenida Miguel de Cervantes"],
        "Santa María de Gracia": ["Plaza de Santa María de Gracia", "Avenida de la Libertad"],
        "Vistabella": ["Calle Vistabella", "Avenida de Floridablanca"],
        "La Flota": ["Calle de la Flota", "Avenida Juan de Borbón"],
        "Infante Juan Manuel": ["Avenida Infante Juan Manuel", "Calle Ceballos"],
        "San Andrés": ["Calle San Andrés", "Calle de Jara"],
        "Santiago el Mayor": ["Calle Santiago", "Calle de Obispo Frutos"],
        "La Fama": ["Calle de la Fama", "Calle de Floridablanca"],
        "San Antón": ["Calle San Antón", "Calle de Acisclo Díaz"],
    },
    "San Sebastián": {
        "Centro": ["Avenida de la Libertad", "Calle San Martín", "Calle Hernani"],
        "Parte Vieja": ["Calle Mayor", "Calle Fermín Calbetón", "Calle 31 de Agosto"],
        "Gros": ["Calle de Zabaleta", "Calle Segundo Izpizua", "Calle de Peña y Goñi"],
        "Amara": ["Paseo de Anoeta", "Calle Sancho el Sabio", "Calle de Easo"],
        "Antiguo": ["Paseo del Faro", "Calle de Matía"],
        "Egia": ["Calle de Egia", "Calle de Tejería"],
        "Ibaeta": ["Paseo de Ibaeta", "Avenida de Tolosa"],
        "Aiete": ["Calle de Aiete", "Paseo del Faro"],
        "Intxaurrondo": ["Avenida de Tolosa", "Carretera de Hernani"],
        "El Antiguo": ["Paseo de Eduardo Chillida", "Calle de Matía"],
    },
    "Santander": {
        "Centro": ["Calle Burgos", "Calle San Fernando", "Calle Isabel II"],
        "El Sardinero": ["Paseo de Pereda", "Avenida de los Castros", "Calle Castelar"],
        "Cuatro Caminos": ["Avenida de los Castros", "Calle Marqués de la Hermida"],
        "Castilla-Hermida": ["Calle Castilla", "Paseo del General Dávila"],
        "Monte": ["Subida al Faro", "Calle Monte"],
        "Numancia": ["Calle Alta", "Calle de Peñas Arriba"],
        "San Martín": ["Calle San Martín", "Paseo del General Dávila"],
        "Puerto Chico": ["Calle Castelar", "Paseo de Pereda"],
    },
    "Palma de Mallorca": {
        "Centro": ["Passeig del Born", "Carrer de Sant Miquel", "Carrer dels Oms"],
        "Santa Catalina": ["Carrer de Sant Magí", "Carrer de la Fàbrica"],
        "El Terreno": ["Carrer de Joan Miró", "Passeig Marítim"],
        "Son Espanyolet": ["Carrer d'Espartero", "Carrer de Joan Crespí"],
        "El Molinar": ["Carrer del Molinar", "Carrer de la Sirena"],
        "Portixol": ["Carrer de Vicari Joaquim Fuster", "Passeig del Portixol"],
        "Son Armadams": ["Carrer d'Andrea Doria", "Avinguda de Joan Miró"],
        "La Lonja": ["Passeig Sagrera", "Carrer de Sant Joan"],
        "Son Vida": ["Carrer de Son Vida", "Camí de Son Vida"],
        "Genova": ["Carrer de Gènova", "Camí de Gènova"],
    },
}
