/**
 * elements.js — Referencias a nodos del DOM
 * Se evalúa al cargar el script (después del DOM está disponible dentro de DOMContentLoaded,
 * pero se inicializa aquí como objeto lazy para que los módulos accedan a él).
 */
const elements = {
    // Búsqueda principal
    locationInput:    document.getElementById('locationInput'),
    citySuggestions:  document.getElementById('citySuggestions'),
    searchBtn:        document.getElementById('searchBtn'),
    toggleFilters:    document.getElementById('toggleFilters'),
    filtersPanel:     document.getElementById('filtersPanel'),
    // Filtros
    maxPrice:         document.getElementById('maxPrice'),
    minBedrooms:      document.getElementById('minBedrooms'),
    minBathrooms:     document.getElementById('minBathrooms'),
    availableFrom:    document.getElementById('availableFrom'),
    minArea:          document.getElementById('minArea'),
    maxArea:          document.getElementById('maxArea'),
    propertyType:     document.getElementById('propertyType'),
    petsAllowed:      document.getElementById('petsAllowed'),
    strictPets:       document.getElementById('strictPets'),
    needElevator:     document.getElementById('needElevator'),
    preferTerrace:    document.getElementById('preferTerrace'),
    preferBalcony:    document.getElementById('preferBalcony'),
    preferTransport:  document.getElementById('preferTransport'),
    preferServices:   document.getElementById('preferServices'),
    longStay:         document.getElementById('longStay'),
    seaView:          document.getElementById('seaView'),
    seaViewToggle:    document.getElementById('seaViewToggle'),
    clearFiltersBtn:  document.getElementById('clearFiltersBtn'),
    shareUrlBtn:      document.getElementById('shareUrlBtn'),
    // Resultados
    resultsSection:   document.getElementById('resultsSection'),
    resultsTitle:     document.getElementById('resultsTitle'),
    resultsSubtitle:  document.getElementById('resultsSubtitle'),
    resultsGrid:      document.getElementById('resultsGrid'),
    loadingState:     document.getElementById('loadingState'),
    emptyState:       document.getElementById('emptyState'),
    directLinks:      document.getElementById('directLinks'),
    directLinksGrid:  document.getElementById('directLinksGrid'),
    platformErrors:   document.getElementById('platformErrors'),
    sortBy:           document.getElementById('sortBy'),
    // Quick filters
    quickFilters:     document.getElementById('quickFilters'),
    qfPriceMin:       document.getElementById('qfPriceMin'),
    qfPriceMax:       document.getElementById('qfPriceMax'),
    qfPriceLabel:     document.getElementById('qfPriceLabel'),
    qfAreaMin:        document.getElementById('qfAreaMin'),
    qfAreaMax:        document.getElementById('qfAreaMax'),
    qfAreaLabel:      document.getElementById('qfAreaLabel'),
    // Paginación
    pagination:       document.getElementById('pagination'),
    prevPage:         document.getElementById('prevPage'),
    nextPage:         document.getElementById('nextPage'),
    pageInfo:         document.getElementById('pageInfo'),
    // Modal propiedad
    propertyModal:    document.getElementById('propertyModal'),
    modalBody:        document.getElementById('modalBody'),
    modalClose:       document.getElementById('modalClose'),
    // Vista mapa
    mapContainer:     document.getElementById('mapContainer'),
    mapEl:            document.getElementById('map'),
    gridViewBtn:      document.getElementById('gridViewBtn'),
    mapViewBtn:       document.getElementById('mapViewBtn'),
    // UI extra
    darkModeToggle:   document.getElementById('darkModeToggle'),
    // Favoritos
    favoritesNavLink: document.getElementById('favoritesNavLink'),
    favCount:         document.getElementById('favCount'),
    favoritesPanel:   document.getElementById('favoritesPanel'),
    favoritesGrid:    document.getElementById('favoritesGrid'),
    favoritesEmpty:   document.getElementById('favoritesEmpty'),
    closeFavorites:   document.getElementById('closeFavorites'),
    // Comparador
    compareBtn:       document.getElementById('compareBtn'),
    compareCount:     document.getElementById('compareCount'),
    compareModal:     document.getElementById('compareModal'),
    compareBody:      document.getElementById('compareBody'),
    closeCompare:     document.getElementById('closeCompare'),
    // Auth
    loginBtn:         document.getElementById('loginBtn'),
    userMenuLogged:   document.getElementById('userMenuLogged'),
    userAvatarBtn:    document.getElementById('userAvatarBtn'),
    userDropdown:     document.getElementById('userDropdown'),
    userDisplayName:  document.getElementById('userDisplayName'),
    userDropdownInfo: document.getElementById('userDropdownInfo'),
    adminPanelLink:   document.getElementById('adminPanelLink'),
    logoutBtn:        document.getElementById('logoutBtn'),
    loginModal:       document.getElementById('loginModal'),
    loginForm:        document.getElementById('loginForm'),
    registerForm:     document.getElementById('registerForm'),
    loginError:       document.getElementById('loginError'),
    registerError:    document.getElementById('registerError'),
    // Tracking
    trackingNavLink:  document.getElementById('trackingNavLink'),
    trackCount:       document.getElementById('trackCount'),
    trackingPanel:    document.getElementById('trackingPanel'),
    trackingBoard:    document.getElementById('trackingBoard'),
    closeTracking:    document.getElementById('closeTracking'),
};
